# Generated by Django 2.2.3 on 2019-07-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, verbose_name='Client ID')),
                ('user_agent', models.CharField(max_length=50, verbose_name='User-Agent')),
                ('document_location', models.CharField(max_length=256, verbose_name='Referer')),
                ('document_referer', models.CharField(max_length=256, verbose_name='Referer')),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
